name: CI

on:
  push:
    branches:
    - serverProcessing
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Connect to host via SSH and update containers
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          command: |
          
            if [ -d ./rutube-download ]
            then 
              cd rutube-download
              docker-compose down
              git pull
              git branch -a 
              git checkout serverProcessing
            else
              git clone https://github.com/boris-on/rutube-download.git
              cd rutube-download
            fi
            
            docker-compose up -d --build
