name: CI

on:
  push:
    branches:
    - main
    
jobs:
  
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Connect to host via SSH and update containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd rutube-download
            
            docker-compose down
            docker container prune
            
            git pull
            
            docker-compose up
        
